/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Point2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author PC
 */
public class Carga extends javax.swing.JFrame
{

    /**
     * Creates new form Carga
     */
    private static boolean iniciarT = true;
    Timer t = new Timer(70, null);
    int i = 0;
    String s="Cargado";
    public Carga()
    {
        initComponents();
        barradeCarga.setUI(new BasicProgressBarUI()
        {
            @Override
            protected void paintDeterminate(Graphics g, JComponent c)
            {
                Graphics2D gp2d = (Graphics2D)g;
                gp2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                int anch = barradeCarga.getWidth();
                int alto = barradeCarga.getHeight();
                int espAnch =anch - 20;
                int espAlto =alto - 20;
                double por = barradeCarga.getPercentComplete();
                espAnch = (int) (espAnch*por);
                Point2D inicio = new Point2D.Double(6, 6);
                Point2D fin = new Point2D.Double(6, 6 + espAlto);
                float[] posGrad = {0.0f,0.25f,1.0f};
                Color[] cl = {Color.BLACK, Color.RED,Color.BLACK};
                LinearGradientPaint grad = new LinearGradientPaint(inicio,fin,posGrad,cl);
                gp2d.setPaint(grad);
                RoundRectangle2D rec =new RoundRectangle2D.Double(10, 10, espAnch, espAlto, espAlto+10, espAlto);
                gp2d.fill(rec);
                gp2d.setColor(Color.BLACK);
                RoundRectangle2D borde = new RoundRectangle2D.Double(5, 5, anch-10, alto-10, espAlto+10, espAlto);
                Stroke grosor = new BasicStroke(5.0f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_MITER);
                gp2d.setStroke(grosor);
                gp2d.draw(borde);
                ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/car_icon-icons.com_61086 (1).png"));
                gp2d.drawImage(img.getImage(), espAnch-35, -8, null);
            }
        });
        
        t.start();
        t.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                i++;
                barradeCarga.setValue(i);
                porcentaje.setText(i+"%");
                if (i%4==0)
                {
                    s="Cargando";
                } else 
                {
                    s+=".";
                }
                txtCarg.setText(s);
                if (i==100)
                {
                    t.stop();
                    cerrar();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        barradeCarga = new javax.swing.JProgressBar();
        txtCarg = new javax.swing.JLabel();
        porcentaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(226, 222, 219));

        barradeCarga.setBackground(new java.awt.Color(226, 222, 219));
        barradeCarga.setForeground(new java.awt.Color(226, 222, 219));

        txtCarg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCarg.setText("Cargando...");

        porcentaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        porcentaje.setText("100%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCarg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(porcentaje))
                    .addComponent(barradeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarg)
                    .addComponent(porcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barradeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Carga().setVisible(true);
            }
        });
    }
    
    private void cerrar()
    {
        iniciarT=false;
        new IntrPrincipal().setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barradeCarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JLabel txtCarg;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the in
     */
    public static boolean getIniciarT()
    {
        return iniciarT;
    }

    /**
     * @param aIniciarT the in to set
     */
    public static void setIniciarT(boolean aIniciarT)
    {
        iniciarT = aIniciarT;
    }
}
