/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import BDagencia.ServicioDAO;
import BDagencia.PinturaDAO;
import BDagencia.AutoDAO;
import agencia.Auto;
import metodos.Validaciones;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class PnlBusAut extends javax.swing.JPanel
{

    /**
     * Creates new form PnlBusAut
     */
    JTextField re = new JTextField();
    public PnlBusAut()
    {
        initComponents();
        re.setBorder(placas.getBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        placas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        anio = new javax.swing.JLabel();
        departamento = new javax.swing.JLabel();
        fechaS = new javax.swing.JLabel();
        fech_pres = new javax.swing.JLabel();
        tipSer_col = new javax.swing.JLabel();
        pagado = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        suc = new javax.swing.JLabel();
        menErrorP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 222, 219));

        placas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        placas.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                placasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                placasFocusLost(evt);
            }
        });
        placas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                placasActionPerformed(evt);
            }
        });
        placas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                placasKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                placasKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Placa:");

        modelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modelo.setText("Modelo: ");

        anio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        anio.setText("Año: ");

        departamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        departamento.setText("Departamento: ");

        fechaS.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        fech_pres.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        tipSer_col.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        pagado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(51, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarActionPerformed(evt);
            }
        });

        suc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        suc.setText("Sucursal: ");

        menErrorP.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pagado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipSer_col, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fech_pres, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(fechaS, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(suc, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anio)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menErrorP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menErrorP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelo)
                .addGap(18, 18, 18)
                .addComponent(anio)
                .addGap(36, 36, 36)
                .addComponent(departamento)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fech_pres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tipSer_col, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pagado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_placasActionPerformed
    {//GEN-HEADEREND:event_placasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarActionPerformed
        if (Validaciones.pinError(placas, menErrorP, "XXX-XXX-XXX", "Ingresa una placa", false))
        {
            Auto autoEnc;
            autoEnc = AutoDAO.obtenerAutoPorPlacas(placas.getText());
            String depAutoEnc = AutoDAO.obtenerDepartamentoPorPlacas(placas.getText());
            busca(autoEnc, depAutoEnc);
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void placasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_placasKeyTyped
    {//GEN-HEADEREND:event_placasKeyTyped
        if (evt.getKeyChar() != ' ' && evt.getKeyChar() != '\n' && evt.getKeyChar() != ((char) 8))
        {
            menErrorP.setText("");
            placas.setBorder(re.getBorder());
        }
        Validaciones.vaP(evt, 11, placas.getText());
        if (evt.getKeyChar() == ' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_placasKeyTyped

    private void placasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_placasKeyPressed
    {//GEN-HEADEREND:event_placasKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (placas.getText().equals(""))
            {
                placas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
                menErrorP.setText("Ingresa una placa");
            }
            btnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_placasKeyPressed

    private void placasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_placasFocusLost
    {//GEN-HEADEREND:event_placasFocusLost
        if (placas.getText().equals("") || !Validaciones.valPal(placas.getText()))
        {
            placas.setForeground(new java.awt.Color(153, 153, 153));
            placas.setText("XXX-XXX-XXX");
        }
    }//GEN-LAST:event_placasFocusLost

    private void placasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_placasFocusGained
    {//GEN-HEADEREND:event_placasFocusGained
        if (placas.getText().equals("XXX-XXX-XXX"))
        {
            placas.setText("");
            placas.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_placasFocusGained

    private boolean busca(Auto auto, String depAuto)
    {
        if(auto != null){
            if(depAuto.equals("Pintura")){
                departamento.setText("Departamento: " + "Pintura");
                fech_pres.setText("Fecha de Ingreso: " + PinturaDAO.obtenerFechaEntrada(auto.getPlacas()));
                fechaS.setText("Fecha de salida: " + PinturaDAO.obtenerFechaSalida(auto.getPlacas()));
                tipSer_col.setText("Color: " + PinturaDAO.obtenerPintura(auto.getPlacas()));
                tipSer_col.setHorizontalAlignment(JLabel.CENTER);
                pagado.setText("");
                suc.setText("Sucursal: " + auto.getSucursal().getNombre());
                modelo.setText("Modelo: " + auto.getModelo());
                anio.setText("Año: " + auto.getAnio());
                return true;
            }
            else if(depAuto.equals("Servicio")){
                departamento.setText("Departamento: " + "Servicio");
                fechaS.setText("");
                fech_pres.setText("Presupuesto: " + ServicioDAO.getPresupuesto(auto.getPlacas()));
                fech_pres.setHorizontalAlignment(JLabel.CENTER);
                tipSer_col.setText("Tipo de servicio: " + ServicioDAO.obtenerTipo(auto.getPlacas()));
                String pagadito = (ServicioDAO.isPagado(auto.getPlacas())) ? "SI" : "NO";
                pagado.setText("Pagado: " + pagadito);
                suc.setText("Sucursal: " + auto.getSucursal().getNombre());
                modelo.setText("Modelo: " + auto.getModelo());
                anio.setText("Año: " + auto.getAnio());
                return true;
            }
            else{
                JOptionPane.showMessageDialog(this, "No se encontro", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "No se encontro", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel departamento;
    private javax.swing.JLabel fech_pres;
    private javax.swing.JLabel fechaS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menErrorP;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel pagado;
    private javax.swing.JTextField placas;
    private javax.swing.JLabel suc;
    private javax.swing.JLabel tipSer_col;
    // End of variables declaration//GEN-END:variables
}
