/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import interfaces.IntrPrincipal;
import BDagencia.AutoDAO;
import agencia.Auto;
import agencia.Pintura;
import agencia.Servicio;
import metodos.Validaciones;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class PnlElmAut extends javax.swing.JPanel
{

    /**
     * Creates new form PnlElmPS
     */
    boolean at;
    JTextField re =new JTextField();

    public PnlElmAut(boolean at)
    {
        initComponents();
        this.at = at;
        re.setBorder(placas.getBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        placas = new javax.swing.JTextField();
        btnElm = new javax.swing.JButton();
        menErrorP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 222, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingresa la placa del auto a eliminar:");

        placas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        placas.setForeground(new java.awt.Color(153, 153, 153));
        placas.setText("XXX-XXX-XXX");
        placas.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                placasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                placasFocusLost(evt);
            }
        });
        placas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                placasActionPerformed(evt);
            }
        });
        placas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                placasKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                placasKeyPressed(evt);
            }
        });

        btnElm.setBackground(new java.awt.Color(51, 153, 255));
        btnElm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnElm.setText("Eliminar");
        btnElm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        btnElm.setBorderPainted(false);
        btnElm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnElm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnElmActionPerformed(evt);
            }
        });

        menErrorP.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnElm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menErrorP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(placas, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menErrorP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnElm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_placasActionPerformed
    {//GEN-HEADEREND:event_placasActionPerformed

    }//GEN-LAST:event_placasActionPerformed

    private void btnElmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnElmActionPerformed
    {//GEN-HEADEREND:event_btnElmActionPerformed
        if (Validaciones.pinError(placas, menErrorP, "XXX-XXX-XXX", "Llenar el campo de texto", false))
        {
            if (AutoDAO.eliminarAuto(placas.getText()))
            {
                JOptionPane.showMessageDialog(this, "Se elimino el auto con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                placas.setText("");
                placasFocusLost(null);
            } else
            {
                JOptionPane.showMessageDialog(this, "No se encontro el auto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnElmActionPerformed

    private void placasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_placasKeyTyped
    {//GEN-HEADEREND:event_placasKeyTyped
        if (evt.getKeyChar() != ' ' && evt.getKeyChar() != '\n' && evt.getKeyChar() != ((char) 8))
        {
            menErrorP.setText("");
            placas.setBorder(re.getBorder());
        }
        Validaciones.vaP(evt, 11, placas.getText());
        if (evt.getKeyChar() == ' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_placasKeyTyped

    private void placasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_placasKeyPressed
    {//GEN-HEADEREND:event_placasKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            if (placas.getText().equals(""))
            {
                placas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
                menErrorP.setText("Llenar el campo de texto");
            }
            btnElmActionPerformed(null);
        }
    }//GEN-LAST:event_placasKeyPressed

    private void placasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_placasFocusLost
    {//GEN-HEADEREND:event_placasFocusLost
        if (placas.getText().equals("") || !Validaciones.valPal(placas.getText()))
        {
            placas.setForeground(new java.awt.Color(153, 153, 153));
            placas.setText("XXX-XXX-XXX");
        }
    }//GEN-LAST:event_placasFocusLost

    private void placasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_placasFocusGained
    {//GEN-HEADEREND:event_placasFocusGained
        if (placas.getText().equals("XXX-XXX-XXX"))
        {
            placas.setText("");
            placas.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_placasFocusGained

    private boolean elm()
    {
        for (int i = 0; i < IntrPrincipal.getSuc().size(); i++)
        {
            for (int j = 0; j < IntrPrincipal.getAut().get(i).size(); j++)
            {
                if (at)
                {
                    if (IntrPrincipal.getAut().get(i).get(j) instanceof Pintura
                            && ((Auto) IntrPrincipal.getAut().get(i).get(j)).getPlacas().equals(placas.getText()))
                    {
                        IntrPrincipal.getAut().get(i).remove(j);
                        return true;
                    }
                } else
                {
                    if (IntrPrincipal.getAut().get(i).get(j) instanceof Servicio
                            && ((Auto) IntrPrincipal.getAut().get(i).get(j)).getPlacas().equals(placas.getText()))
                    {
                        IntrPrincipal.getAut().get(i).remove(j);
                        return true;
                    }
                }
            }
        }
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menErrorP;
    private javax.swing.JTextField placas;
    // End of variables declaration//GEN-END:variables
}
