/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import BDagencia.SucursalDAO;
import BDagencia.AutoDAO;
import agencia.Auto;
import agencia.Sucursal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PnlMover extends javax.swing.JPanel
{

    /**
     * Creates new form PnlMover
     */
    public PnlMover()
    {
        initComponents();
        List<Sucursal> sucursalesDisponibles = SucursalDAO.desplegarTodasLasSucursales();
        for (int i = 0; i < sucursalesDisponibles.size(); i++)
        {
            mosSucO.addItem(sucursalesDisponibles.get(i).getNombre());
        }
        mostD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        mosSucO = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        mosSucD = new javax.swing.JComboBox<>();
        btnMover = new javax.swing.JButton();

        setBackground(new java.awt.Color(226, 222, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mapa.png"))); // NOI18N
        jLabel1.setText("Elige la sucursal de origen del auto:");

        mosSucO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mosSucO.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                mosSucOItemStateChanged(evt);
            }
        });
        mosSucO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mosSucOActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mapa.png"))); // NOI18N
        jLabel2.setText("Elige la sucursal donde se movera el auto:");

        mosSucD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnMover.setBackground(new java.awt.Color(51, 153, 255));
        btnMover.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMover.setText("Mover");
        btnMover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        btnMover.setBorderPainted(false);
        btnMover.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mosSucD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mosSucO, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnMover, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mosSucO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mosSucD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnMover, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mosSucOActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mosSucOActionPerformed
    {//GEN-HEADEREND:event_mosSucOActionPerformed
        mostD();
    }//GEN-LAST:event_mosSucOActionPerformed

    private void mosSucOItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_mosSucOItemStateChanged
    {//GEN-HEADEREND:event_mosSucOItemStateChanged

    }//GEN-LAST:event_mosSucOItemStateChanged

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMoverActionPerformed
    {//GEN-HEADEREND:event_btnMoverActionPerformed
        List<Auto> autosSucO = AutoDAO.obtenerAutosPorSucursal(SucursalDAO.obtenerSucursalPorNombre(mosSucO.getSelectedItem().toString()).getNombre());
        int i=0;
        if (SucursalDAO.getCantidadSucursales() >= 2)
        {
            if (!autosSucO.isEmpty())
            {
                for (i = 0; i < autosSucO.size(); i++)
                {
                    if(!AutoDAO.modificarSucursal(mosSucD.getSelectedItem().toString(), autosSucO.get(i).getPlacas())){
                        JOptionPane.showMessageDialog(this, "Error al mover el auto con placas: " + autosSucO.get(i).getPlacas(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, mosSucO.getSelectedItem()+" no tiene carros para mover", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "No hay suficientes sucursales registradas", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(i == autosSucO.size()){
            JOptionPane.showMessageDialog(this, "Se han movido los autos correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMoverActionPerformed

    private void mostD()
    {
        mosSucD.removeAllItems();
        List<Sucursal> sucursalesDisponibles = SucursalDAO.desplegarTodasLasSucursales();
        for (int i = 0; i < sucursalesDisponibles.size(); i++)
        {
            if(!sucursalesDisponibles.get(i).getNombre().equals(mosSucO.getSelectedItem().toString()))
                mosSucD.addItem(sucursalesDisponibles.get(i).getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> mosSucD;
    private javax.swing.JComboBox<String> mosSucO;
    // End of variables declaration//GEN-END:variables
}
