/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import BDagencia.SucursalDAO;
import agencia.Sucursal;
import metodos.Validaciones;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class PnlRegSuc extends javax.swing.JPanel
{

    /**
     * Creates new form PnlRegSuc
     */
    JTextField re = new JTextField();

    public PnlRegSuc()
    {
        initComponents();
        re.setBorder(nomSuc.getBorder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        nomSuc = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        menError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 222, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingresa el nombre de la sucursal:");

        nomSuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomSuc.setForeground(new java.awt.Color(153, 153, 153));
        nomSuc.setText("Ingresa el nombre de la sucursal.");
        nomSuc.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                nomSucFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                nomSucFocusLost(evt);
            }
        });
        nomSuc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nomSucActionPerformed(evt);
            }
        });
        nomSuc.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomSucKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomSucKeyPressed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });

        menError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menError, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(91, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(menError, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomSucActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nomSucActionPerformed
    {//GEN-HEADEREND:event_nomSucActionPerformed

    }//GEN-LAST:event_nomSucActionPerformed

    private void nomSucKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomSucKeyPressed
    {//GEN-HEADEREND:event_nomSucKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnRegistrarActionPerformed(null);
        }
    }//GEN-LAST:event_nomSucKeyPressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed
        if (Validaciones.valPal(nomSuc.getText()) && !nomSuc.getText().equals("Ingresa el nombre de la sucursal."))
        {
            Sucursal suc = new Sucursal(nomSuc.getText());
            SucursalDAO.guardarSucursal(suc);
            //IntrPrincipal.getSuc().add(nomSuc.getText());
            //IntrPrincipal.getAut().add(new ArrayList<Auto>());
            menError.setText("");
            nomSuc.setText("");
            nomSucFocusLost(null);
            btnRegistrar.requestFocus();
            JOptionPane.showMessageDialog(this, "Se registro con exito la sucursal", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else
        {
            nomSuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            menError.setText("Error... Ingresa un nombre");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void nomSucKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomSucKeyTyped
    {//GEN-HEADEREND:event_nomSucKeyTyped
        if (evt.getKeyChar() != ' ' && evt.getKeyChar() != '\n' && evt.getKeyChar() != ((char) 8))
        {
            menError.setText("");
            nomSuc.setBorder(re.getBorder());
        }
        Validaciones.va(evt, 28, nomSuc.getText());
        if (nomSuc.getText().equals("") && evt.getKeyChar() == ' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_nomSucKeyTyped

    private void nomSucFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nomSucFocusLost
    {//GEN-HEADEREND:event_nomSucFocusLost
        if (nomSuc.getText().equals("") || !Validaciones.valPal(nomSuc.getText()))
        {
            nomSuc.setForeground(new java.awt.Color(153, 153, 153));
            nomSuc.setText("Ingresa el nombre de la sucursal.");
        }
    }//GEN-LAST:event_nomSucFocusLost

    private void nomSucFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nomSucFocusGained
    {//GEN-HEADEREND:event_nomSucFocusGained
        nomSuc.setText("");
        nomSuc.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_nomSucFocusGained

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menError;
    private javax.swing.JTextField nomSuc;
    // End of variables declaration//GEN-END:variables
}
